version: "3.8"
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes:
      - .:/var/www/html
      - ./symfony.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:8.2-fpm
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - database
      - composer
  composer:
    image: composer:latest
    volumes:
      - .:/app
  database:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=oneOfAKind
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  db_data:
